//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("11-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11551053572so3ctmz3mx {
            get {
                object obj = ResourceManager.GetObject("-11551053572so3ctmz3mx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11551053572so3ctmz3mx_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("-11551053572so3ctmz3mx-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _16a7ef72_7003_41ae_b04d_f11398d665ea {
            get {
                object obj = ResourceManager.GetObject("16a7ef72-7003-41ae-b04d-f11398d665ea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2_resize_1 {
            get {
                object obj = ResourceManager.GetObject("2_resize-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _280290963_848629059431132_5941502794218549388_n {
            get {
                object obj = ResourceManager.GetObject("280290963_848629059431132_5941502794218549388_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _285361123_1921706731348406_7288956600754255673_n {
            get {
                object obj = ResourceManager.GetObject("285361123_1921706731348406_7288956600754255673_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _285361123_1921706731348406_7288956600754255673_n1 {
            get {
                object obj = ResourceManager.GetObject("285361123_1921706731348406_7288956600754255673_n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _285361123_1921706731348406_7288956600754255673_n2 {
            get {
                object obj = ResourceManager.GetObject("285361123_1921706731348406_7288956600754255673_n2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _82f64514_db42_4e82_bf7c_4e6bda717e70 {
            get {
                object obj = ResourceManager.GetObject("82f64514-db42-4e82-bf7c-4e6bda717e70", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8571_png_860 {
            get {
                object obj = ResourceManager.GetObject("8571.png_860", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Admin {
            get {
                object obj = ResourceManager.GetObject("Admin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ADMIN__1_ {
            get {
                object obj = ResourceManager.GetObject("ADMIN (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ADMIN__2_ {
            get {
                object obj = ResourceManager.GetObject("ADMIN (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ADMIN__3_ {
            get {
                object obj = ResourceManager.GetObject("ADMIN (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ADMIN__4_ {
            get {
                object obj = ResourceManager.GetObject("ADMIN (4)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Architecture_Window_1 {
            get {
                object obj = ResourceManager.GetObject("Architecture_Window_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap car_seat_icon_137808 {
            get {
                object obj = ResourceManager.GetObject("car_seat_icon_137808", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_chair_computer_icons_seat {
            get {
                object obj = ResourceManager.GetObject("kisspng-chair-computer-icons-seat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_chair_computer_icons_seat1 {
            get {
                object obj = ResourceManager.GetObject("kisspng-chair-computer-icons-seat1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_human_eye_computer_icons_symbol_eye_examination_eyelashes_icon_5b56a0ca0845e0_0569646415324039140339 {
            get {
                object obj = ResourceManager.GetObject("kisspng-human-eye-computer-icons-symbol-eye-examination-eyelashes-icon-5b56a0ca08" +
                        "45e0.0569646415324039140339", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MG_4102_2_1024x682 {
            get {
                object obj = ResourceManager.GetObject("MG_4102-2-1024x682", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_computer_icons_scalable_graphics_symbol_eye_icon_logo_black_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("png-clipart-computer-icons-scalable-graphics-symbol-eye-icon-logo-black-removebg-" +
                        "preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_computer_icons_scalable_graphics_symbol_eye_icon_logo_black_thumbnail_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("png-clipart-computer-icons-scalable-graphics-symbol-eye-icon-logo-black-thumbnail" +
                        "-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_computer_icons_scalable_graphics_symbol_eye_icon_logo_black_thumbnail_removebg_preview__1_ {
            get {
                object obj = ResourceManager.GetObject("png-clipart-computer-icons-scalable-graphics-symbol-eye-icon-logo-black-thumbnail" +
                        "-removebg-preview (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_train_train {
            get {
                object obj = ResourceManager.GetObject("png-clipart-train-train", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_cute_cartoon_flower_png_image_4076149_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("pngtree-cute-cartoon-flower-png-image_4076149-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_train_cartoon_png_image_1110648 {
            get {
                object obj = ResourceManager.GetObject("pngtree-train-cartoon-png-image_1110648", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pvrvkr7tlwjQALJkhhh_o {
            get {
                object obj = ResourceManager.GetObject("pvrvkr7tlwjQALJkhhh-o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thailand {
            get {
                object obj = ResourceManager.GetObject("thailand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Train_Icon_2 {
            get {
                object obj = ResourceManager.GetObject("Train_Icon_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap w644 {
            get {
                object obj = ResourceManager.GetObject("w644", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap เข้าสู่ระบบ {
            get {
                object obj = ResourceManager.GetObject("เข้าสู่ระบบ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap เลือกขบวนโดยสาร {
            get {
                object obj = ResourceManager.GetObject("เลือกขบวนโดยสาร", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap เลือกขบวนโดยสาร__1_ {
            get {
                object obj = ResourceManager.GetObject("เลือกขบวนโดยสาร (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap เลือกตู้_ที่นั่ง {
            get {
                object obj = ResourceManager.GetObject("เลือกตู้+ที่นั่ง", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap การรถไฟแห่ง_ประเทศน้องนีแลนด์ {
            get {
                object obj = ResourceManager.GetObject("การรถไฟแห่ง ประเทศน้องนีแลนด์", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ดีไซน์ที่ไม่มีชื่อ {
            get {
                object obj = ResourceManager.GetObject("ดีไซน์ที่ไม่มีชื่อ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ประวัติการจองตั๋ว {
            get {
                object obj = ResourceManager.GetObject("ประวัติการจองตั๋ว", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ยกเลิก_การจองตั๋ว {
            get {
                object obj = ResourceManager.GetObject("ยกเลิก การจองตั๋ว", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ยกเลิก_การจองตั๋ว__1_ {
            get {
                object obj = ResourceManager.GetObject("ยกเลิก การจองตั๋ว (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap รถไฟไทย {
            get {
                object obj = ResourceManager.GetObject("รถไฟไทย", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap รถไฟมันมีหลายราง_แต่ถ้ามีเธอข้างๆ_เราไม่มีหลายใจ {
            get {
                object obj = ResourceManager.GetObject("รถไฟมันมีหลายราง แต่ถ้ามีเธอข้างๆ เราไม่มีหลายใจ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap รถไฟมันมีหลายราง_แต่ถ้ามีเธอข้างๆ_เราไม่มีหลายใจ1 {
            get {
                object obj = ResourceManager.GetObject("รถไฟมันมีหลายราง แต่ถ้ามีเธอข้างๆ เราไม่มีหลายใจ1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ลืมรหัสผ่าน {
            get {
                object obj = ResourceManager.GetObject("ลืมรหัสผ่าน", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ลืมรหัสผ่านเบ๋อ {
            get {
                object obj = ResourceManager.GetObject("ลืมรหัสผ่านเบ๋อ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap สมัครสมาชิก {
            get {
                object obj = ResourceManager.GetObject("สมัครสมาชิก", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
